name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      working-directory: ./1
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile -t himalayk/accionlabs:$IMAGE_TAG
        docker push himalayk/accionlabs:$IMAGE_TAG
    - run: echo "image pushed" $IMAGE_TAG
