name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ImageTag: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      working-directory: ./1
      run: |
        docker build . --file Dockerfile -t himalayk/accionlabs:${{env.ImageTag}}
        docker push himalayk/accionlabs:${{env.ImageTag}}

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/himalayk/accionlabs:${{env.ImageTag}}
        severity: CRITICAL
        exit-code: '1'
        ignore-unfixed: true
