name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      working-directory: ./1
      run: |
        docker build . --file Dockerfile -t himalayk/accionlabs:$(date +%s)
        docker push himalayk/accionlabs:$(date +%s)
    - run: echo "image pushed" $(date +%s)
